version: '3.8'
services:
  crm_customers:
    container_name: crm_customers
    build:
      dockerfile: Dockerfile
    image: customers:latest
    ports:
      - 3501:3501
    depends_on:
      - redis-db
    networks:
      - crm-network
  redis-db:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass admin
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local
networks:
  crm-network:
    driver: bridge