spring:
  profiles:
    active: dev

---

spring:
  application:
    name: crm-customers
  config:
    activate:
      on-profile: dev
    import: configserver:http://localhost:3500
  main:
    allow-circular-references: true
  cloud:
    config:
      fail-fast: true
      name: "crm_customers"
  data:
    redis:
      url: redis://localhost:6379
      password: admin
  kafka:
    bootstrap-servers: http://localhost:9092
    producer:
      properties:
        spring:
          json:
            add:
              type:
                headers: true
      acks: all
      bootstrap-servers: http://localhost:9092
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 3501
  servlet:
    context-path: /api
logging:
  level:
    org:
      springframework: info
app:
  all-methods-log:
    enabled: true
  messaging:
    enabled: true
